- name: Update, upgrade, and maintain packages
  hosts: all
  become: yes
  tasks:
    - name: Update the package list
      apt:
        update_cache: yes

    - name: Upgrade installed packages
      apt:
        upgrade: dist

    - name: Autoremove unnecessary packages
      apt:
        autoremove: yes

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Report reboot requirement
      debug:
        msg: "Reboot is required."
      when: reboot_required.stat.exists

    - name: Report no reboot requirement
      debug:
        msg: "No reboot is required."
      when: not reboot_required.stat.exists
